{{- if and .Values.agent.cache.clearJob.create .Values.agent.cache.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "jenkins.fullname" . }}-cache-cronjob
  namespace: {{ template "jenkins.master.slaveKubernetesNamespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" . }}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ include "jenkins.fullname" . }}-cache-cronjob"
spec:
  concurrencyPolicy : "Forbid"
  failedJobsHistoryLimit : 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.agent.cache.clearJob.schedule | quote }}
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      backoffLimit: 6
      template:
        metadata:
          labels:
            "app.kubernetes.io/name": '{{ template "jenkins.name" . }}'
            "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
            "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
            "app.kubernetes.io/instance": "{{ .Release.Name }}"
            "app.kubernetes.io/component": "{{ include "jenkins.fullname" . }}-cache-cronjob"
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: cache-volume
              persistentVolumeClaim:
                claimName: {{ include "jenkins.fullname" . }}-cache-pvc
          containers:
            - name: clear-cache
              image: "{{ .Values.agent.cache.clearJob.image }}:{{ .Values.agent.cache.clearJob.tag }}"
              volumeMounts:
                - name: cache-volume
                  mountPath: {{ .Values.agent.workingDir }}
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 500m
                  memory: 512Mi
              workingDir: {{ .Values.agent.workingDir }}
              command: {{ toYaml .Values.agent.cache.clearJob.command | nindent 16 }}
              args: {{ toYaml .Values.agent.cache.clearJob.args | nindent 16 }}
{{- end }}